name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: dependendencies
      run: sudo apt-get install -y xml2rfc
      
    - name: Make
      run: make && tar cvfz internetdrafts.tar.gz *.xml *.txt *.html

    - name: Upload compiled documents
      uses: actions/upload-artifact@v3
      with:
        name: internet-drafts
        path: internetdrafts.tar.gz
